// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updates} from '../models';

export function CheckInstallerUpdate():Promise<updates.UpdateInfo>;

export function GetLatestInstallerRelease():Promise<updates.GitHubRelease>;
