// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstallPath() {
  return window['go']['installer_paths']['Paths']['GetInstallPath']();
}

export function Startup(arg1) {
  return window['go']['installer_paths']['Paths']['Startup'](arg1);
}
