// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {installer_paths} from '../models';
import {context} from '../models';

export function GetInstallPath():Promise<installer_paths.InstallPathInfo>;

export function Startup(arg1:context.Context):Promise<void>;
