// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {installer} from '../models';
import {context} from '../models';

export function DownloadInstaller(arg1:string):Promise<installer.DownloadResult>;

export function GetLatestRelease():Promise<installer.LatestReleaseInfo>;

export function RemoveVoidPresence(arg1:string):Promise<void>;

export function RunInstallerUpdater(arg1:string):Promise<void>;

export function RunNsis(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
