// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadInstaller(arg1) {
  return window['go']['installer']['Installer']['DownloadInstaller'](arg1);
}

export function GetLatestRelease() {
  return window['go']['installer']['Installer']['GetLatestRelease']();
}

export function RemoveVoidPresence(arg1) {
  return window['go']['installer']['Installer']['RemoveVoidPresence'](arg1);
}

export function RunInstallerUpdater(arg1) {
  return window['go']['installer']['Installer']['RunInstallerUpdater'](arg1);
}

export function RunNsis(arg1) {
  return window['go']['installer']['Installer']['RunNsis'](arg1);
}

export function Startup(arg1) {
  return window['go']['installer']['Installer']['Startup'](arg1);
}
