// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadInstaller(arg1) {
  return window['go']['main']['Installer']['DownloadInstaller'](arg1);
}

export function GetLatestRelease() {
  return window['go']['main']['Installer']['GetLatestRelease']();
}

export function RunNsis(arg1) {
  return window['go']['main']['Installer']['RunNsis'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['Installer']['Startup'](arg1);
}
