// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function DownloadInstaller(arg1:string):Promise<main.DownloadResult>;

export function GetLatestRelease():Promise<main.LatestReleaseInfo>;

export function RunNsis(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
