// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInstallerUpdate() {
  return window['go']['main']['Updates']['CheckInstallerUpdate']();
}

export function GetLatestInstallerRelease() {
  return window['go']['main']['Updates']['GetLatestInstallerRelease']();
}
