// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckInstallerUpdate():Promise<main.UpdateInfo>;

export function GetLatestInstallerRelease():Promise<main.GitHubRelease>;
